logging:
  level:
    web: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:recipe
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2