server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ 'health' ]

logging:
  level:
    web: DEBUG

spring:
  data:
    rest:
      base-path: /api
      max-page-size: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:recipe
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2