server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: [ 'health' ]

logging:
  level:
    web: INFO

spring:
  data:
    rest:
      base-path: /api
      max-page-size: 1000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate